server:
  port: ${PORT:8762} # Indicate the default PORT where this service will be started

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # telling the server not to register himself in the service
    fetchRegistry: false
  

    
    
      
     

