spring:
  application:
    name: USER-ZUUL
server:
  port: 8051
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
      instance:
      hostname: localhost
  
zuul:
    prefix: /api
    routes:
      user-DB-Server:
         path: /server/**
         url: http://localhost:8080
      user-client:
         path: /client/**
      service-id: USER-CLIENT
            
         
    
    
    
      
     

